export const ejerciciosPorEdad = {
  '4-6 años': [
    // 10 ejercicios fáciles
    { pregunta: '¿Cuánto es 2 + 3?', opciones: ['4', '5', '6'], respuestaCorrecta: '5', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 5 - 1?', opciones: ['4', '3', '5'], respuestaCorrecta: '4', dificultad: 'fácil' },
    { pregunta: '¿Cuál es el número mayor?', opciones: ['7', '3', '5'], respuestaCorrecta: '7', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 1 + 1?', opciones: ['2', '3', '1'], respuestaCorrecta: '2', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 3 - 2?', opciones: ['2', '1', '0'], respuestaCorrecta: '1', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 4 + 2?', opciones: ['6', '5', '7'], respuestaCorrecta: '6', dificultad: 'fácil' },
    { pregunta: '¿Cuántos dedos tienes en una mano?', opciones: ['4', '5', '6'], respuestaCorrecta: '5', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 0 + 4?', opciones: ['3', '4', '5'], respuestaCorrecta: '4', dificultad: 'fácil' },
    { pregunta: '¿Cuál es el número más pequeño?', opciones: ['2', '1', '3'], respuestaCorrecta: '1', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 5 - 3?', opciones: ['1', '2', '3'], respuestaCorrecta: '2', dificultad: 'fácil' },

    // 10 ejercicios media
    { pregunta: '¿Qué número sigue después del 4?', opciones: ['3', '5', '2'], respuestaCorrecta: '5', dificultad: 'media' },
    { pregunta: '¿Cuánto es 0 + 5?', opciones: ['4', '5', '6'], respuestaCorrecta: '5', dificultad: 'media' },
    { pregunta: '¿Cuánto es 6 - 1?', opciones: ['4', '5', '6'], respuestaCorrecta: '5', dificultad: 'media' },
    { pregunta: '¿Cuánto es 7 - 3?', opciones: ['3', '4', '5'], respuestaCorrecta: '4', dificultad: 'media' },
    { pregunta: '¿Cuánto es 8 + 1?', opciones: ['8', '9', '10'], respuestaCorrecta: '9', dificultad: 'media' },
    { pregunta: '¿Cuántos días tiene una semana?', opciones: ['5', '6', '7'], respuestaCorrecta: '7', dificultad: 'media' },
    { pregunta: '¿Cuánto es 2 + 4?', opciones: ['6', '5', '7'], respuestaCorrecta: '6', dificultad: 'media' },
    { pregunta: '¿Cuál es el número impar?', opciones: ['2', '3', '4'], respuestaCorrecta: '3', dificultad: 'media' },
    { pregunta: '¿Cuánto es 9 - 6?', opciones: ['2', '3', '4'], respuestaCorrecta: '3', dificultad: 'media' },
    { pregunta: '¿Cuánto es 1 + 3?', opciones: ['3', '4', '5'], respuestaCorrecta: '4', dificultad: 'media' },

    // 10 ejercicios difíciles
    { pregunta: '¿Qué número es menor?', opciones: ['2', '1', '3'], respuestaCorrecta: '1', dificultad: 'difícil' },
    { pregunta: '¿Cuántos lados tiene un triángulo?', opciones: ['3', '4', '5'], respuestaCorrecta: '3', dificultad: 'difícil' },
    { pregunta: '¿Qué número viene antes del 6?', opciones: ['7', '4', '5'], respuestaCorrecta: '5', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 10 - 7?', opciones: ['3', '4', '2'], respuestaCorrecta: '3', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 8 - 5?', opciones: ['4', '3', '2'], respuestaCorrecta: '3', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 7 - 4?', opciones: ['4', '2', '3'], respuestaCorrecta: '3', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 9 - 7?', opciones: ['1', '2', '3'], respuestaCorrecta: '2', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 11 - 8?', opciones: ['2', '3', '4'], respuestaCorrecta: '3', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 6 - 3?', opciones: ['2', '3', '4'], respuestaCorrecta: '3', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 5 - 2?', opciones: ['3', '4', '2'], respuestaCorrecta: '3', dificultad: 'difícil' },
  ],

  '7-9 años': [
    // 10 ejercicios fáciles
    { pregunta: '¿Cuánto es 6 x 2?', opciones: ['12', '8', '14'], respuestaCorrecta: '12', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 9 ÷ 3?', opciones: ['2', '3', '4'], respuestaCorrecta: '3', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 7 + 6?', opciones: ['13', '12', '14'], respuestaCorrecta: '13', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 5 + 5?', opciones: ['10', '9', '11'], respuestaCorrecta: '10', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 4 x 2?', opciones: ['8', '6', '7'], respuestaCorrecta: '8', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 10 ÷ 2?', opciones: ['5', '4', '6'], respuestaCorrecta: '5', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 3 + 4?', opciones: ['6', '7', '8'], respuestaCorrecta: '7', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 8 - 2?', opciones: ['5', '6', '7'], respuestaCorrecta: '6', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 1 + 9?', opciones: ['10', '11', '9'], respuestaCorrecta: '10', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 7 - 4?', opciones: ['2', '3', '4'], respuestaCorrecta: '3', dificultad: 'fácil' },

    // 10 ejercicios media
    { pregunta: '¿Cuánto es 10 - 4?', opciones: ['5', '6', '7'], respuestaCorrecta: '6', dificultad: 'media' },
    { pregunta: '¿Cuál es el doble de 5?', opciones: ['10', '15', '20'], respuestaCorrecta: '10', dificultad: 'media' },
    { pregunta: '¿Cuánto es 4 x 3?', opciones: ['7', '12', '10'], respuestaCorrecta: '12', dificultad: 'media' },
    { pregunta: '¿Cuánto es 20 ÷ 5?', opciones: ['5', '4', '3'], respuestaCorrecta: '4', dificultad: 'media' },
    { pregunta: '¿Cuánto es 9 + 8?', opciones: ['16', '17', '18'], respuestaCorrecta: '17', dificultad: 'media' },
    { pregunta: '¿Cuánto es 5 x 4?', opciones: ['20', '19', '21'], respuestaCorrecta: '20', dificultad: 'media' },
    { pregunta: '¿Cuánto es 18 ÷ 3?', opciones: ['5', '6', '7'], respuestaCorrecta: '6', dificultad: 'media' },
    { pregunta: '¿Cuánto es 15 - 7?', opciones: ['7', '8', '9'], respuestaCorrecta: '8', dificultad: 'media' },
    { pregunta: '¿Cuánto es 6 + 7?', opciones: ['12', '13', '14'], respuestaCorrecta: '13', dificultad: 'media' },
    { pregunta: '¿Cuánto es 8 x 2?', opciones: ['15', '16', '17'], respuestaCorrecta: '16', dificultad: 'media' },

    // 10 ejercicios difíciles
    { pregunta: '¿Cuánto es 11 - 7?', opciones: ['4', '3', '5'], respuestaCorrecta: '4', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 3 x 3?', opciones: ['6', '9', '12'], respuestaCorrecta: '9', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 8 ÷ 2?', opciones: ['3', '4', '5'], respuestaCorrecta: '4', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 14 + 6?', opciones: ['20', '19', '21'], respuestaCorrecta: '20', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 25 - 9?', opciones: ['14', '15', '16'], respuestaCorrecta: '16', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 12 ÷ 4?', opciones: ['2', '3', '4'], respuestaCorrecta: '3', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 9 x 4?', opciones: ['36', '35', '37'], respuestaCorrecta: '36', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 18 - 7?', opciones: ['10', '11', '12'], respuestaCorrecta: '11', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 13 + 8?', opciones: ['20', '21', '22'], respuestaCorrecta: '21', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 15 ÷ 3?', opciones: ['5', '4', '6'], respuestaCorrecta: '5', dificultad: 'difícil' },
  ],

  '10-12 años': [
    // 10 ejercicios fáciles
    { pregunta: '¿Cuál es el resultado de 15 + 27?', opciones: ['42', '37', '43'], respuestaCorrecta: '42', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 48 ÷ 6?', opciones: ['6', '8', '7'], respuestaCorrecta: '8', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 9 x 7?', opciones: ['63', '72', '56'], respuestaCorrecta: '63', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 25 + 15?', opciones: ['40', '41', '39'], respuestaCorrecta: '40', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 30 ÷ 5?', opciones: ['5', '6', '7'], respuestaCorrecta: '6', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 8 x 5?', opciones: ['40', '35', '45'], respuestaCorrecta: '40', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 12 + 18?', opciones: ['29', '30', '31'], respuestaCorrecta: '30', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 7 x 4?', opciones: ['27', '28', '29'], respuestaCorrecta: '28', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 50 ÷ 10?', opciones: ['4', '5', '6'], respuestaCorrecta: '5', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 11 + 22?', opciones: ['33', '34', '35'], respuestaCorrecta: '33', dificultad: 'fácil' },

    // 10 ejercicios media
    { pregunta: '¿Cuánto es 64 ÷ 8?', opciones: ['8', '7', '6'], respuestaCorrecta: '8', dificultad: 'media' },
    { pregunta: '¿Qué número falta: 5, 10, __, 20?', opciones: ['12', '15', '18'], respuestaCorrecta: '15', dificultad: 'media' },
    { pregunta: '¿Cuánto es 100 - 45?', opciones: ['55', '65', '60'], respuestaCorrecta: '55', dificultad: 'media' },
    { pregunta: '¿Cuánto es 36 ÷ 4?', opciones: ['8', '9', '6'], respuestaCorrecta: '9', dificultad: 'media' },
    { pregunta: '¿Cuánto es 7 x 6?', opciones: ['42', '41', '40'], respuestaCorrecta: '42', dificultad: 'media' },
    { pregunta: '¿Cuánto es 81 ÷ 9?', opciones: ['8', '9', '10'], respuestaCorrecta: '9', dificultad: 'media' },
    { pregunta: '¿Cuánto es 14 + 26?', opciones: ['40', '41', '39'], respuestaCorrecta: '40', dificultad: 'media' },
    { pregunta: '¿Cuánto es 18 - 7?', opciones: ['10', '11', '12'], respuestaCorrecta: '11', dificultad: 'media' },
    { pregunta: '¿Cuánto es 6 x 7?', opciones: ['42', '41', '43'], respuestaCorrecta: '42', dificultad: 'media' },
    { pregunta: '¿Cuánto es 55 ÷ 5?', opciones: ['9', '10', '11'], respuestaCorrecta: '11', dificultad: 'media' },

    // 10 ejercicios difíciles
    { pregunta: '¿Cuánto es 11 x 3?', opciones: ['33', '30', '36'], respuestaCorrecta: '33', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 72 ÷ 9?', opciones: ['8', '6', '9'], respuestaCorrecta: '8', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 25 + 17?', opciones: ['42', '43', '41'], respuestaCorrecta: '42', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 49 ÷ 7?', opciones: ['6', '7', '8'], respuestaCorrecta: '7', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 15 x 4?', opciones: ['60', '59', '61'], respuestaCorrecta: '60', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 90 ÷ 10?', opciones: ['8', '9', '10'], respuestaCorrecta: '9', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 28 + 34?', opciones: ['61', '62', '63'], respuestaCorrecta: '62', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 36 - 15?', opciones: ['20', '21', '22'], respuestaCorrecta: '21', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 7 x 8?', opciones: ['54', '56', '58'], respuestaCorrecta: '56', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 18 ÷ 6?', opciones: ['3', '4', '2'], respuestaCorrecta: '3', dificultad: 'difícil' },
  ],

  '13-15 años': [
    // 10 ejercicios fáciles
    { pregunta: '¿Cuánto es 45 + 55?', opciones: ['90', '100', '110'], respuestaCorrecta: '100', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 81 ÷ 9?', opciones: ['9', '8', '7'], respuestaCorrecta: '9', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 12 x 4?', opciones: ['48', '44', '52'], respuestaCorrecta: '48', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 100 - 45?', opciones: ['55', '50', '60'], respuestaCorrecta: '55', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 25 + 75?', opciones: ['95', '100', '110'], respuestaCorrecta: '100', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 14 x 3?', opciones: ['42', '44', '40'], respuestaCorrecta: '42', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 60 ÷ 6?', opciones: ['10', '9', '11'], respuestaCorrecta: '10', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 20 + 35?', opciones: ['55', '54', '60'], respuestaCorrecta: '55', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 8 x 7?', opciones: ['54', '56', '58'], respuestaCorrecta: '56', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 15 ÷ 3?', opciones: ['4', '5', '6'], respuestaCorrecta: '5', dificultad: 'fácil' },

    // 10 ejercicios media
    { pregunta: '¿Cuánto es 125 - 47?', opciones: ['78', '77', '79'], respuestaCorrecta: '78', dificultad: 'media' },
    { pregunta: '¿Cuánto es 15 x 6?', opciones: ['90', '85', '95'], respuestaCorrecta: '90', dificultad: 'media' },
    { pregunta: '¿Cuánto es 144 ÷ 12?', opciones: ['12', '11', '10'], respuestaCorrecta: '12', dificultad: 'media' },
    { pregunta: '¿Cuánto es 100 + 150?', opciones: ['240', '250', '260'], respuestaCorrecta: '250', dificultad: 'media' },
    { pregunta: '¿Cuánto es 200 - 76?', opciones: ['124', '125', '126'], respuestaCorrecta: '124', dificultad: 'media' },
    { pregunta: '¿Cuánto es 18 x 5?', opciones: ['85', '90', '95'], respuestaCorrecta: '90', dificultad: 'media' },
    { pregunta: '¿Cuánto es 81 ÷ 9?', opciones: ['9', '8', '10'], respuestaCorrecta: '9', dificultad: 'media' },
    { pregunta: '¿Cuánto es 55 + 65?', opciones: ['110', '120', '130'], respuestaCorrecta: '120', dificultad: 'media' },
    { pregunta: '¿Cuánto es 72 - 48?', opciones: ['25', '24', '26'], respuestaCorrecta: '24', dificultad: 'media' },
    { pregunta: '¿Cuánto es 63 ÷ 7?', opciones: ['8', '9', '7'], respuestaCorrecta: '9', dificultad: 'media' },

    // 10 ejercicios difíciles
    { pregunta: '¿Cuánto es 17 x 9?', opciones: ['153', '154', '155'], respuestaCorrecta: '153', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 225 ÷ 15?', opciones: ['15', '14', '16'], respuestaCorrecta: '15', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 145 + 287?', opciones: ['422', '432', '412'], respuestaCorrecta: '432', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 400 - 275?', opciones: ['125', '115', '135'], respuestaCorrecta: '125', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 22 x 11?', opciones: ['242', '252', '232'], respuestaCorrecta: '242', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 324 ÷ 18?', opciones: ['18', '17', '16'], respuestaCorrecta: '18', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 134 + 289?', opciones: ['423', '413', '433'], respuestaCorrecta: '423', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 90 - 43?', opciones: ['47', '46', '48'], respuestaCorrecta: '47', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 27 x 8?', opciones: ['214', '216', '218'], respuestaCorrecta: '216', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 144 ÷ 12?', opciones: ['11', '12', '13'], respuestaCorrecta: '12', dificultad: 'difícil' },
  ],

  '16-18 años': [
    // 10 ejercicios fáciles
    { pregunta: '¿Cuánto es 125 + 175?', opciones: ['290', '300', '310'], respuestaCorrecta: '300', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 144 ÷ 12?', opciones: ['10', '12', '14'], respuestaCorrecta: '12', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 20 x 6?', opciones: ['120', '110', '130'], respuestaCorrecta: '120', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 90 - 45?', opciones: ['45', '44', '46'], respuestaCorrecta: '45', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 15 x 7?', opciones: ['105', '100', '110'], respuestaCorrecta: '105', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 81 ÷ 9?', opciones: ['8', '9', '10'], respuestaCorrecta: '9', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 33 + 27?', opciones: ['60', '59', '61'], respuestaCorrecta: '60', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 56 ÷ 8?', opciones: ['6', '7', '8'], respuestaCorrecta: '7', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 18 x 4?', opciones: ['72', '70', '74'], respuestaCorrecta: '72', dificultad: 'fácil' },
    { pregunta: '¿Cuánto es 200 - 100?', opciones: ['100', '99', '101'], respuestaCorrecta: '100', dificultad: 'fácil' },

    // 10 ejercicios media
    { pregunta: '¿Cuánto es 144 - 76?', opciones: ['68', '69', '70'], respuestaCorrecta: '68', dificultad: 'media' },
    { pregunta: '¿Cuánto es 13 x 7?', opciones: ['89', '90', '91'], respuestaCorrecta: '91', dificultad: 'media' },
    { pregunta: '¿Cuánto es 225 ÷ 15?', opciones: ['14', '15', '16'], respuestaCorrecta: '15', dificultad: 'media' },
    { pregunta: '¿Cuánto es 180 + 220?', opciones: ['390', '400', '410'], respuestaCorrecta: '400', dificultad: 'media' },
    { pregunta: '¿Cuánto es 132 - 58?', opciones: ['74', '73', '75'], respuestaCorrecta: '74', dificultad: 'media' },
    { pregunta: '¿Cuánto es 17 x 8?', opciones: ['134', '136', '138'], respuestaCorrecta: '136', dificultad: 'media' },
    { pregunta: '¿Cuánto es 90 ÷ 6?', opciones: ['14', '15', '16'], respuestaCorrecta: '15', dificultad: 'media' },
    { pregunta: '¿Cuánto es 56 + 44?', opciones: ['100', '99', '101'], respuestaCorrecta: '100', dificultad: 'media' },
    { pregunta: '¿Cuánto es 81 - 35?', opciones: ['46', '45', '47'], respuestaCorrecta: '46', dificultad: 'media' },
    { pregunta: '¿Cuánto es 108 ÷ 9?', opciones: ['12', '11', '10'], respuestaCorrecta: '12', dificultad: 'media' },

    // 10 ejercicios difíciles
    { pregunta: '¿Cuánto es 23 x 11?', opciones: ['253', '243', '263'], respuestaCorrecta: '253', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 324 ÷ 18?', opciones: ['17', '18', '19'], respuestaCorrecta: '18', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 475 + 325?', opciones: ['790', '800', '810'], respuestaCorrecta: '800', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 600 - 375?', opciones: ['225', '235', '215'], respuestaCorrecta: '225', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 28 x 13?', opciones: ['364', '374', '354'], respuestaCorrecta: '364', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 441 ÷ 21?', opciones: ['20', '21', '22'], respuestaCorrecta: '21', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 150 + 389?', opciones: ['529', '539', '519'], respuestaCorrecta: '539', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 180 - 75?', opciones: ['105', '110', '100'], respuestaCorrecta: '105', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 36 x 7?', opciones: ['252', '262', '242'], respuestaCorrecta: '252', dificultad: 'difícil' },
    { pregunta: '¿Cuánto es 196 ÷ 14?', opciones: ['14', '13', '15'], respuestaCorrecta: '14', dificultad: 'difícil' },
  ],
};

